/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import backEnd.BookArray;
import javax.swing.JOptionPane;

/**
 *
 * @author Gia Naicker
 */
public class FindRecommendedBooks extends javax.swing.JFrame {

    BookArray ba;

    /**
     * Creates new form FindRecommendedBooks
     */
    public FindRecommendedBooks() {
        initComponents();
        ba = new BookArray();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lookingForBooksLabel = new javax.swing.JLabel();
        searchFavouriteBookTitleLabel = new javax.swing.JLabel();
        searchBookTitleTextField = new javax.swing.JTextField();
        weGotYouLabel = new javax.swing.JLabel();
        searchGenreButton = new javax.swing.JButton();
        youMightLikeLabel = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        recommendedBooksTextArea = new javax.swing.JTextArea();
        searchGenreLabel = new javax.swing.JLabel();
        searchGenreComboBox = new javax.swing.JComboBox<>();
        searchBookButton = new javax.swing.JButton();
        orLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        lookingForBooksLabel.setFont(new java.awt.Font("Impact", 0, 35)); // NOI18N
        lookingForBooksLabel.setForeground(new java.awt.Color(0, 0, 0));
        lookingForBooksLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lookingForBooksLabel.setText("Looking for similar books? ");

        searchFavouriteBookTitleLabel.setBackground(new java.awt.Color(255, 255, 255));
        searchFavouriteBookTitleLabel.setFont(new java.awt.Font("Impact", 0, 15)); // NOI18N
        searchFavouriteBookTitleLabel.setForeground(new java.awt.Color(0, 0, 0));
        searchFavouriteBookTitleLabel.setText("Favourite book:");

        searchBookTitleTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBookTitleTextFieldActionPerformed(evt);
            }
        });
        searchBookTitleTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchBookTitleTextFieldKeyPressed(evt);
            }
        });

        weGotYouLabel.setFont(new java.awt.Font("Impact", 0, 15)); // NOI18N
        weGotYouLabel.setForeground(new java.awt.Color(0, 0, 0));
        weGotYouLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        weGotYouLabel.setText("Don't worry, we've got you ;)");

        searchGenreButton.setText("Search");
        searchGenreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchGenreButtonActionPerformed(evt);
            }
        });

        youMightLikeLabel.setFont(new java.awt.Font("Impact", 0, 15)); // NOI18N
        youMightLikeLabel.setForeground(new java.awt.Color(0, 0, 0));
        youMightLikeLabel.setText("You might like:");

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        recommendedBooksTextArea.setEditable(false);
        recommendedBooksTextArea.setColumns(20);
        recommendedBooksTextArea.setRows(5);
        jScrollPane2.setViewportView(recommendedBooksTextArea);

        searchGenreLabel.setBackground(new java.awt.Color(255, 255, 255));
        searchGenreLabel.setFont(new java.awt.Font("Impact", 0, 15)); // NOI18N
        searchGenreLabel.setForeground(new java.awt.Color(0, 0, 0));
        searchGenreLabel.setText("Search  genre:");

        searchGenreComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Romance", "Non-fiction", "Drama", "Mystery", "Fiction", "Science Fiction", "Biography / Autobiography", "Lifestyle", "Horror / Thriller", "Comedy" }));

        searchBookButton.setText("Search");
        searchBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBookButtonActionPerformed(evt);
            }
        });

        orLabel.setFont(new java.awt.Font("Impact", 0, 20)); // NOI18N
        orLabel.setForeground(new java.awt.Color(0, 0, 0));
        orLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        orLabel.setText("OR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lookingForBooksLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(youMightLikeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(searchGenreLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(searchFavouriteBookTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(7, 7, 7)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(searchBookTitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(searchBookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(searchGenreComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(searchGenreButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(weGotYouLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(orLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(237, 237, 237))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lookingForBooksLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(weGotYouLabel)
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchFavouriteBookTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBookTitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchGenreComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchGenreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchGenreButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(youMightLikeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(backButton)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        new CyberBooksHome().setVisible(true);
        dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void searchGenreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchGenreButtonActionPerformed
        String getGenre = (String) searchGenreComboBox.getSelectedItem();
        String recBooksGenre = ba.recBooksByGenre(getGenre);
        if (recBooksGenre.isBlank()) {
            JOptionPane.showMessageDialog(null, "There are no books in the library with this genre", "Books not found", JOptionPane.INFORMATION_MESSAGE);
        } else {
            recommendedBooksTextArea.setText(recBooksGenre);
        }
    }//GEN-LAST:event_searchGenreButtonActionPerformed

    private void searchBookTitleTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBookTitleTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBookTitleTextFieldActionPerformed

    private void searchBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBookButtonActionPerformed
        String bookName = searchBookTitleTextField.getText();
        int index = ba.search(bookName);

        if (index != -1) {
            recommendedBooksTextArea.setText(ba.recBooksByName(index));
        } else {
            JOptionPane.showMessageDialog(null, "The book you searched for does not exist in this library :(", "Book not found", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_searchBookButtonActionPerformed

    private void searchBookTitleTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchBookTitleTextFieldKeyPressed

    }//GEN-LAST:event_searchBookTitleTextFieldKeyPressed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lookingForBooksLabel;
    private javax.swing.JLabel orLabel;
    private javax.swing.JTextArea recommendedBooksTextArea;
    private javax.swing.JButton searchBookButton;
    private javax.swing.JTextField searchBookTitleTextField;
    private javax.swing.JLabel searchFavouriteBookTitleLabel;
    private javax.swing.JButton searchGenreButton;
    private javax.swing.JComboBox<String> searchGenreComboBox;
    private javax.swing.JLabel searchGenreLabel;
    private javax.swing.JLabel weGotYouLabel;
    private javax.swing.JLabel youMightLikeLabel;
    // End of variables declaration//GEN-END:variables
}
