/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import backEnd.BookArray;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Gia Naicker
 */
public class RateBooks extends javax.swing.JFrame {

    BookArray ba;

    /**
     * Creates new form RateBooks
     */
    public RateBooks() {
        initComponents();
        setLocationRelativeTo(null);

        ba = new BookArray();
        DefaultListModel<String> model = new DefaultListModel<String>();
        String[] titles = ba.getBookTitlesAsArray();
        for (int i = 0; i < titles.length; i++) {
            model.addElement(titles[i]);
        }
        rateBooksList.setModel(model);
        highestRatedBooksTextArea.setText(ba.highestRatings());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pleaseSelectBookLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        rateBooksList = new javax.swing.JList<>();
        backButton = new javax.swing.JButton();
        selectValueLabel = new javax.swing.JLabel();
        chooseRatingSpinner = new javax.swing.JSpinner();
        confirmRatingButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        highestRatedBooksTextArea = new javax.swing.JTextArea();
        highestRatedBooksLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));

        pleaseSelectBookLabel.setFont(new java.awt.Font("Impact", 0, 28)); // NOI18N
        pleaseSelectBookLabel.setForeground(new java.awt.Color(0, 0, 0));
        pleaseSelectBookLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pleaseSelectBookLabel.setText("Please select a book from the list to rate:");

        rateBooksList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(rateBooksList);

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        selectValueLabel.setFont(new java.awt.Font("Impact", 0, 15)); // NOI18N
        selectValueLabel.setForeground(new java.awt.Color(0, 0, 0));
        selectValueLabel.setText("Select a value from 0 - 5:");

        chooseRatingSpinner.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        chooseRatingSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 5, 1));

        confirmRatingButton.setText("Confirm rating");
        confirmRatingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmRatingButtonActionPerformed(evt);
            }
        });

        highestRatedBooksTextArea.setEditable(false);
        highestRatedBooksTextArea.setColumns(20);
        highestRatedBooksTextArea.setRows(5);
        jScrollPane2.setViewportView(highestRatedBooksTextArea);

        highestRatedBooksLabel.setFont(new java.awt.Font("Impact", 0, 15)); // NOI18N
        highestRatedBooksLabel.setForeground(new java.awt.Color(0, 0, 0));
        highestRatedBooksLabel.setText("HIghest Rated Books:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pleaseSelectBookLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(confirmRatingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(chooseRatingSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(selectValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(highestRatedBooksLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 30, Short.MAX_VALUE)))))
                        .addGap(14, 14, 14)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(pleaseSelectBookLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(selectValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chooseRatingSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(confirmRatingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(highestRatedBooksLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmRatingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmRatingButtonActionPerformed
        //Gets name of book, searches, finds index, sets rating to spinner value.
        String bookName = rateBooksList.getSelectedValue();
        int index = ba.search(bookName);
        String rating = "" + chooseRatingSpinner.getValue();

        if (bookName == null) {
            JOptionPane.showMessageDialog(null, "Please select a book to rate.", "You have not selected a book", JOptionPane.INFORMATION_MESSAGE);
        } else {
            ba.rateBooks(index, rating);
            JOptionPane.showMessageDialog(null, "Thank you for rating a book!", "Rating successfully added", JOptionPane.INFORMATION_MESSAGE);
        }

        highestRatedBooksTextArea.setText(ba.highestRatings());
    }//GEN-LAST:event_confirmRatingButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        new CyberBooksHome().setVisible(true);
        dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JSpinner chooseRatingSpinner;
    private javax.swing.JButton confirmRatingButton;
    private javax.swing.JLabel highestRatedBooksLabel;
    private javax.swing.JTextArea highestRatedBooksTextArea;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel pleaseSelectBookLabel;
    private javax.swing.JList<String> rateBooksList;
    private javax.swing.JLabel selectValueLabel;
    // End of variables declaration//GEN-END:variables
}
